name: Google Credentials Secret

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest
    steps:
      - name: Get Credentials JSON File 
        run: |
          sed -i "s/TOKEN/${{secrets.GOOGLE_SHEETS_API_CREDENTIALS}}/g" "credentials.json"

